<link rel="stylesheet" href="../../../public/assets/style2.css">
<div class="container-fluid px-1 px-md-4 py-5 mx-auto">
    <div class="row d-flex justify-content-center px-3">
        <div class="card">
            <h2 class="ml-auto mr-4 mt-3 mb-0 text-danger"><?php echo $data["location"]["name"]?></h2>
            <p class="ml-auto mr-4 mb-0 med-font">Sunrise:<?php  echo $data["astronomy"]["astro"]["sunrise"]?></p>
            <p class="ml-auto mr-4 mb-0 med-font">Sunset:<?php  echo $data["astronomy"]["astro"]["sunset"] ?></p>
            <p class="ml-auto mr-4 mb-0 med-font">Moon Rise:<?php echo $data["astronomy"]["astro"]["moonrise"] ?></p>
            <p class="ml-auto mr-4 mb-0 med-font">Moon phase<?php echo $data["astronomy"]["astro"]["moon_phase"] ?></p>
  
            <p class="time-font mb-0 ml-4 mt-auto"> <?php echo " ".date("H-i",strtotime($data["location"]["localtime"])) ?></p>
            <p class="ml-4 mb-4"><?php echo date("F j, Y",strtotime($data["location"]["localtime"])) ?></p>
        </div>
    </div>
    <div class = "justify-content-center d-flex  px-3">
    <?php
include('footer.phtml');
?>
   </div>
    </div>