<link rel="stylesheet" href="../../../public/assets/css/styl1.css">
<div class="justify-content-center d-flex  px-3">
      <?php include('header.phtml'); ?>
 </div>

<div class="container d-flex justify-content-center">
 
    <ul class="list-group mt-5 text-white">
    <h2 class="text-center">All locations</h2>
        <?php foreach ($data as $key => $value) {  
        ?>
        <a href="productDetail?url=<?php echo $value->url?>">
        <li class="list-group-item d-flex justify-content-between align-content-center">
                <div class="ml-2">
                    <h6 class="mb-0"><?php echo $value->name?></h6>
                    <p class="mb-0"><b>Region</b>:<?php echo " ".$value->region." " ?> &emsp; <b>Country</b>: <?php echo " ".$value->country ?> </p>
                 

                    

            </div>
        </li>
        </a>
        <?php } ?>
    </ul>
</div>